// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/paxos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaxosService_SendRequest_FullMethodName = "/paxos.PaxosService/SendRequest"
	PaxosService_GetStatus_FullMethodName   = "/paxos.PaxosService/GetStatus"
	PaxosService_PrintLog_FullMethodName    = "/paxos.PaxosService/PrintLog"
	PaxosService_PrintDB_FullMethodName     = "/paxos.PaxosService/PrintDB"
	PaxosService_PrintStatus_FullMethodName = "/paxos.PaxosService/PrintStatus"
	PaxosService_PrintView_FullMethodName   = "/paxos.PaxosService/PrintView"
)

// PaxosServiceClient is the client API for PaxosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Client-facing service - only what clients need
type PaxosServiceClient interface {
	// Client to Node communication
	SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Status, error)
	// Utility functions (if clients need them)
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	PrintLog(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	PrintDB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	PrintStatus(ctx context.Context, in *PrintStatusRequest, opts ...grpc.CallOption) (*Status, error)
	PrintView(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
}

type paxosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosServiceClient(cc grpc.ClientConnInterface) PaxosServiceClient {
	return &paxosServiceClient{cc}
}

func (c *paxosServiceClient) SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PaxosService_SendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PaxosService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) PrintLog(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PaxosService_PrintLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) PrintDB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PaxosService_PrintDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) PrintStatus(ctx context.Context, in *PrintStatusRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PaxosService_PrintStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) PrintView(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PaxosService_PrintView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosServiceServer is the server API for PaxosService service.
// All implementations must embed UnimplementedPaxosServiceServer
// for forward compatibility.
//
// Client-facing service - only what clients need
type PaxosServiceServer interface {
	// Client to Node communication
	SendRequest(context.Context, *Request) (*Status, error)
	// Utility functions (if clients need them)
	GetStatus(context.Context, *Empty) (*Status, error)
	PrintLog(context.Context, *Empty) (*Status, error)
	PrintDB(context.Context, *Empty) (*Status, error)
	PrintStatus(context.Context, *PrintStatusRequest) (*Status, error)
	PrintView(context.Context, *Empty) (*Status, error)
	mustEmbedUnimplementedPaxosServiceServer()
}

// UnimplementedPaxosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaxosServiceServer struct{}

func (UnimplementedPaxosServiceServer) SendRequest(context.Context, *Request) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedPaxosServiceServer) GetStatus(context.Context, *Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPaxosServiceServer) PrintLog(context.Context, *Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintLog not implemented")
}
func (UnimplementedPaxosServiceServer) PrintDB(context.Context, *Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintDB not implemented")
}
func (UnimplementedPaxosServiceServer) PrintStatus(context.Context, *PrintStatusRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintStatus not implemented")
}
func (UnimplementedPaxosServiceServer) PrintView(context.Context, *Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintView not implemented")
}
func (UnimplementedPaxosServiceServer) mustEmbedUnimplementedPaxosServiceServer() {}
func (UnimplementedPaxosServiceServer) testEmbeddedByValue()                      {}

// UnsafePaxosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosServiceServer will
// result in compilation errors.
type UnsafePaxosServiceServer interface {
	mustEmbedUnimplementedPaxosServiceServer()
}

func RegisterPaxosServiceServer(s grpc.ServiceRegistrar, srv PaxosServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaxosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaxosService_ServiceDesc, srv)
}

func _PaxosService_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).SendRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_PrintLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).PrintLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_PrintLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).PrintLog(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_PrintDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).PrintDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_PrintDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).PrintDB(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_PrintStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).PrintStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_PrintStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).PrintStatus(ctx, req.(*PrintStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_PrintView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).PrintView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_PrintView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).PrintView(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PaxosService_ServiceDesc is the grpc.ServiceDesc for PaxosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaxosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.PaxosService",
	HandlerType: (*PaxosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequest",
			Handler:    _PaxosService_SendRequest_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PaxosService_GetStatus_Handler,
		},
		{
			MethodName: "PrintLog",
			Handler:    _PaxosService_PrintLog_Handler,
		},
		{
			MethodName: "PrintDB",
			Handler:    _PaxosService_PrintDB_Handler,
		},
		{
			MethodName: "PrintStatus",
			Handler:    _PaxosService_PrintStatus_Handler,
		},
		{
			MethodName: "PrintView",
			Handler:    _PaxosService_PrintView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paxos.proto",
}

const (
	NodeService_HandlePrepare_FullMethodName     = "/paxos.NodeService/HandlePrepare"
	NodeService_HandlePromise_FullMethodName     = "/paxos.NodeService/HandlePromise"
	NodeService_HandleAccept_FullMethodName      = "/paxos.NodeService/HandleAccept"
	NodeService_HandleAccepted_FullMethodName    = "/paxos.NodeService/HandleAccepted"
	NodeService_HandleCommit_FullMethodName      = "/paxos.NodeService/HandleCommit"
	NodeService_HandleNewView_FullMethodName     = "/paxos.NodeService/HandleNewView"
	NodeService_HandleRequest_FullMethodName     = "/paxos.NodeService/HandleRequest"
	NodeService_RequestNewView_FullMethodName    = "/paxos.NodeService/RequestNewView"
	NodeService_GetLeader_FullMethodName         = "/paxos.NodeService/GetLeader"
	NodeService_SendCheckpoint_FullMethodName    = "/paxos.NodeService/SendCheckpoint"
	NodeService_RequestCheckpoint_FullMethodName = "/paxos.NodeService/RequestCheckpoint"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal node-to-node service - Paxos protocol only
type NodeServiceClient interface {
	// Paxos protocol messages
	HandlePrepare(ctx context.Context, in *Prepare, opts ...grpc.CallOption) (*PrepareAck, error)
	HandlePromise(ctx context.Context, in *Promise, opts ...grpc.CallOption) (*Status, error)
	HandleAccept(ctx context.Context, in *Accept, opts ...grpc.CallOption) (*AcceptAck, error)
	HandleAccepted(ctx context.Context, in *Accepted, opts ...grpc.CallOption) (*Status, error)
	HandleCommit(ctx context.Context, in *Commit, opts ...grpc.CallOption) (*Status, error)
	HandleNewView(ctx context.Context, in *NewView, opts ...grpc.CallOption) (*Status, error)
	// Request forwarding (when non-leader receives client request)
	HandleRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Status, error)
	// active catch-up
	RequestNewView(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NewView, error)
	// leader discovery
	GetLeader(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeInfo, error)
	// Bonus: checkpoint distribution
	SendCheckpoint(ctx context.Context, in *Checkpoint, opts ...grpc.CallOption) (*Status, error)
	RequestCheckpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointSnapshot, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) HandlePrepare(ctx context.Context, in *Prepare, opts ...grpc.CallOption) (*PrepareAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareAck)
	err := c.cc.Invoke(ctx, NodeService_HandlePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) HandlePromise(ctx context.Context, in *Promise, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, NodeService_HandlePromise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) HandleAccept(ctx context.Context, in *Accept, opts ...grpc.CallOption) (*AcceptAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptAck)
	err := c.cc.Invoke(ctx, NodeService_HandleAccept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) HandleAccepted(ctx context.Context, in *Accepted, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, NodeService_HandleAccepted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) HandleCommit(ctx context.Context, in *Commit, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, NodeService_HandleCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) HandleNewView(ctx context.Context, in *NewView, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, NodeService_HandleNewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) HandleRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, NodeService_HandleRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RequestNewView(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NewView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewView)
	err := c.cc.Invoke(ctx, NodeService_RequestNewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetLeader(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfo)
	err := c.cc.Invoke(ctx, NodeService_GetLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SendCheckpoint(ctx context.Context, in *Checkpoint, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, NodeService_SendCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RequestCheckpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointSnapshot)
	err := c.cc.Invoke(ctx, NodeService_RequestCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// Internal node-to-node service - Paxos protocol only
type NodeServiceServer interface {
	// Paxos protocol messages
	HandlePrepare(context.Context, *Prepare) (*PrepareAck, error)
	HandlePromise(context.Context, *Promise) (*Status, error)
	HandleAccept(context.Context, *Accept) (*AcceptAck, error)
	HandleAccepted(context.Context, *Accepted) (*Status, error)
	HandleCommit(context.Context, *Commit) (*Status, error)
	HandleNewView(context.Context, *NewView) (*Status, error)
	// Request forwarding (when non-leader receives client request)
	HandleRequest(context.Context, *Request) (*Status, error)
	// active catch-up
	RequestNewView(context.Context, *Empty) (*NewView, error)
	// leader discovery
	GetLeader(context.Context, *Empty) (*NodeInfo, error)
	// Bonus: checkpoint distribution
	SendCheckpoint(context.Context, *Checkpoint) (*Status, error)
	RequestCheckpoint(context.Context, *CheckpointRequest) (*CheckpointSnapshot, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) HandlePrepare(context.Context, *Prepare) (*PrepareAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePrepare not implemented")
}
func (UnimplementedNodeServiceServer) HandlePromise(context.Context, *Promise) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePromise not implemented")
}
func (UnimplementedNodeServiceServer) HandleAccept(context.Context, *Accept) (*AcceptAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleAccept not implemented")
}
func (UnimplementedNodeServiceServer) HandleAccepted(context.Context, *Accepted) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleAccepted not implemented")
}
func (UnimplementedNodeServiceServer) HandleCommit(context.Context, *Commit) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCommit not implemented")
}
func (UnimplementedNodeServiceServer) HandleNewView(context.Context, *NewView) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleNewView not implemented")
}
func (UnimplementedNodeServiceServer) HandleRequest(context.Context, *Request) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleRequest not implemented")
}
func (UnimplementedNodeServiceServer) RequestNewView(context.Context, *Empty) (*NewView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestNewView not implemented")
}
func (UnimplementedNodeServiceServer) GetLeader(context.Context, *Empty) (*NodeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeader not implemented")
}
func (UnimplementedNodeServiceServer) SendCheckpoint(context.Context, *Checkpoint) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCheckpoint not implemented")
}
func (UnimplementedNodeServiceServer) RequestCheckpoint(context.Context, *CheckpointRequest) (*CheckpointSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCheckpoint not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_HandlePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Prepare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).HandlePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_HandlePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).HandlePrepare(ctx, req.(*Prepare))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_HandlePromise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Promise)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).HandlePromise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_HandlePromise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).HandlePromise(ctx, req.(*Promise))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_HandleAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accept)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).HandleAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_HandleAccept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).HandleAccept(ctx, req.(*Accept))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_HandleAccepted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accepted)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).HandleAccepted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_HandleAccepted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).HandleAccepted(ctx, req.(*Accepted))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_HandleCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Commit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).HandleCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_HandleCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).HandleCommit(ctx, req.(*Commit))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_HandleNewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).HandleNewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_HandleNewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).HandleNewView(ctx, req.(*NewView))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_HandleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).HandleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_HandleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).HandleRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RequestNewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RequestNewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RequestNewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RequestNewView(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetLeader(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SendCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Checkpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SendCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SendCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SendCheckpoint(ctx, req.(*Checkpoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RequestCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RequestCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RequestCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RequestCheckpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandlePrepare",
			Handler:    _NodeService_HandlePrepare_Handler,
		},
		{
			MethodName: "HandlePromise",
			Handler:    _NodeService_HandlePromise_Handler,
		},
		{
			MethodName: "HandleAccept",
			Handler:    _NodeService_HandleAccept_Handler,
		},
		{
			MethodName: "HandleAccepted",
			Handler:    _NodeService_HandleAccepted_Handler,
		},
		{
			MethodName: "HandleCommit",
			Handler:    _NodeService_HandleCommit_Handler,
		},
		{
			MethodName: "HandleNewView",
			Handler:    _NodeService_HandleNewView_Handler,
		},
		{
			MethodName: "HandleRequest",
			Handler:    _NodeService_HandleRequest_Handler,
		},
		{
			MethodName: "RequestNewView",
			Handler:    _NodeService_RequestNewView_Handler,
		},
		{
			MethodName: "GetLeader",
			Handler:    _NodeService_GetLeader_Handler,
		},
		{
			MethodName: "SendCheckpoint",
			Handler:    _NodeService_SendCheckpoint_Handler,
		},
		{
			MethodName: "RequestCheckpoint",
			Handler:    _NodeService_RequestCheckpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paxos.proto",
}

const (
	ClientService_SendReply_FullMethodName = "/paxos.ClientService/SendReply"
)

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Client service - for nodes to send replies to clients
type ClientServiceClient interface {
	// Node to Client communication
	SendReply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Status, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) SendReply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ClientService_SendReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility.
//
// Client service - for nodes to send replies to clients
type ClientServiceServer interface {
	// Node to Client communication
	SendReply(context.Context, *Reply) (*Status, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientServiceServer struct{}

func (UnimplementedClientServiceServer) SendReply(context.Context, *Reply) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReply not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}
func (UnimplementedClientServiceServer) testEmbeddedByValue()                       {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_SendReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).SendReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_SendReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).SendReply(ctx, req.(*Reply))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendReply",
			Handler:    _ClientService_SendReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paxos.proto",
}
