// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/paxos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ballot number is a tuple (round, node_id)
type BallotNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallotNumber) Reset() {
	*x = BallotNumber{}
	mi := &file_proto_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallotNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotNumber) ProtoMessage() {}

func (x *BallotNumber) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotNumber.ProtoReflect.Descriptor instead.
func (*BallotNumber) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *BallotNumber) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *BallotNumber) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

// Transaction message containing transfer details
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Client request message
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Request) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Request) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Paxos protocol messages
type Prepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prepare) Reset() {
	*x = Prepare{}
	mi := &file_proto_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare) ProtoMessage() {}

func (x *Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare.ProtoReflect.Descriptor instead.
func (*Prepare) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *Prepare) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

type Promise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	AcceptLog     []*AcceptLogEntry      `protobuf:"bytes,2,rep,name=accept_log,json=acceptLog,proto3" json:"accept_log,omitempty"`
	SenderId      int32                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ExecutedSeq   int32                  `protobuf:"varint,4,opt,name=executed_seq,json=executedSeq,proto3" json:"executed_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promise) Reset() {
	*x = Promise{}
	mi := &file_proto_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promise) ProtoMessage() {}

func (x *Promise) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promise.ProtoReflect.Descriptor instead.
func (*Promise) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *Promise) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Promise) GetAcceptLog() []*AcceptLogEntry {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

func (x *Promise) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Promise) GetExecutedSeq() int32 {
	if x != nil {
		return x.ExecutedSeq
	}
	return 0
}

type PrepareAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Queued        bool                   `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`  // true if prepare was queued for later processing
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareAck) Reset() {
	*x = PrepareAck{}
	mi := &file_proto_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareAck) ProtoMessage() {}

func (x *PrepareAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareAck.ProtoReflect.Descriptor instead.
func (*PrepareAck) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareAck) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *PrepareAck) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *PrepareAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AcceptLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptNum     *BallotNumber          `protobuf:"bytes,1,opt,name=accept_num,json=acceptNum,proto3" json:"accept_num,omitempty"`
	AcceptSeq     int32                  `protobuf:"varint,2,opt,name=accept_seq,json=acceptSeq,proto3" json:"accept_seq,omitempty"`
	AcceptVal     *Request               `protobuf:"bytes,3,opt,name=accept_val,json=acceptVal,proto3" json:"accept_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptLogEntry) Reset() {
	*x = AcceptLogEntry{}
	mi := &file_proto_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptLogEntry) ProtoMessage() {}

func (x *AcceptLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptLogEntry.ProtoReflect.Descriptor instead.
func (*AcceptLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptLogEntry) GetAcceptNum() *BallotNumber {
	if x != nil {
		return x.AcceptNum
	}
	return nil
}

func (x *AcceptLogEntry) GetAcceptSeq() int32 {
	if x != nil {
		return x.AcceptSeq
	}
	return 0
}

func (x *AcceptLogEntry) GetAcceptVal() *Request {
	if x != nil {
		return x.AcceptVal
	}
	return nil
}

type Accept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Request       *Request               `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accept) Reset() {
	*x = Accept{}
	mi := &file_proto_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accept) ProtoMessage() {}

func (x *Accept) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accept.ProtoReflect.Descriptor instead.
func (*Accept) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *Accept) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Accept) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Accept) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type AcceptAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodeId        int32                  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptAck) Reset() {
	*x = AcceptAck{}
	mi := &file_proto_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptAck) ProtoMessage() {}

func (x *AcceptAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptAck.ProtoReflect.Descriptor instead.
func (*AcceptAck) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcceptAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AcceptAck) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type Accepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Request       *Request               `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	NodeId        int32                  `protobuf:"varint,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accepted) Reset() {
	*x = Accepted{}
	mi := &file_proto_paxos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accepted) ProtoMessage() {}

func (x *Accepted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accepted.ProtoReflect.Descriptor instead.
func (*Accepted) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{9}
}

func (x *Accepted) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Accepted) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Accepted) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Accepted) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Request       *Request               `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_proto_paxos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{10}
}

func (x *Commit) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Commit) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Commit) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type NewView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	AcceptLog     []*AcceptLogEntry      `protobuf:"bytes,2,rep,name=accept_log,json=acceptLog,proto3" json:"accept_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewView) Reset() {
	*x = NewView{}
	mi := &file_proto_paxos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewView) ProtoMessage() {}

func (x *NewView) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewView.ProtoReflect.Descriptor instead.
func (*NewView) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{11}
}

func (x *NewView) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *NewView) GetAcceptLog() []*AcceptLogEntry {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Result        bool                   `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_proto_paxos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{12}
}

func (x *Reply) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Reply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Reply) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Reply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Node information
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_paxos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{13}
}

func (x *NodeInfo) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Client information
type ClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_proto_paxos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{14}
}

func (x *ClientInfo) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// System configuration
type SystemConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Clients       []*ClientInfo          `protobuf:"bytes,2,rep,name=clients,proto3" json:"clients,omitempty"`
	F             int32                  `protobuf:"varint,3,opt,name=f,proto3" json:"f,omitempty"` // maximum number of faulty nodes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemConfig) Reset() {
	*x = SystemConfig{}
	mi := &file_proto_paxos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfig) ProtoMessage() {}

func (x *SystemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemConfig.ProtoReflect.Descriptor instead.
func (*SystemConfig) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{15}
}

func (x *SystemConfig) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *SystemConfig) GetClients() []*ClientInfo {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *SystemConfig) GetF() int32 {
	if x != nil {
		return x.F
	}
	return 0
}

// Status messages
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_paxos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{16}
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Empty message for simple RPC calls
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_paxos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{17}
}

// PrintStatus request message
type PrintStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int32                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrintStatusRequest) Reset() {
	*x = PrintStatusRequest{}
	mi := &file_proto_paxos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintStatusRequest) ProtoMessage() {}

func (x *PrintStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintStatusRequest.ProtoReflect.Descriptor instead.
func (*PrintStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{18}
}

func (x *PrintStatusRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

var File_proto_paxos_proto protoreflect.FileDescriptor

const file_proto_paxos_proto_rawDesc = "" +
	"\n" +
	"\x11proto/paxos.proto\x12\x05paxos\"=\n" +
	"\fBallotNumber\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\"Y\n" +
	"\vTransaction\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"z\n" +
	"\aRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x124\n" +
	"\vtransaction\x18\x03 \x01(\v2\x12.paxos.TransactionR\vtransaction\"6\n" +
	"\aPrepare\x12+\n" +
	"\x06ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\"\xac\x01\n" +
	"\aPromise\x12+\n" +
	"\x06ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\x124\n" +
	"\n" +
	"accept_log\x18\x02 \x03(\v2\x15.paxos.AcceptLogEntryR\tacceptLog\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x05R\bsenderId\x12!\n" +
	"\fexecuted_seq\x18\x04 \x01(\x05R\vexecutedSeq\"k\n" +
	"\n" +
	"PrepareAck\x12+\n" +
	"\x06ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\x12\x16\n" +
	"\x06queued\x18\x02 \x01(\bR\x06queued\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x92\x01\n" +
	"\x0eAcceptLogEntry\x122\n" +
	"\n" +
	"accept_num\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\tacceptNum\x12\x1d\n" +
	"\n" +
	"accept_seq\x18\x02 \x01(\x05R\tacceptSeq\x12-\n" +
	"\n" +
	"accept_val\x18\x03 \x01(\v2\x0e.paxos.RequestR\tacceptVal\"{\n" +
	"\x06Accept\x12+\n" +
	"\x06ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\x12(\n" +
	"\arequest\x18\x03 \x01(\v2\x0e.paxos.RequestR\arequest\"X\n" +
	"\tAcceptAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x05R\x06nodeId\"\x96\x01\n" +
	"\bAccepted\x12+\n" +
	"\x06ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\x12(\n" +
	"\arequest\x18\x03 \x01(\v2\x0e.paxos.RequestR\arequest\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\x05R\x06nodeId\"{\n" +
	"\x06Commit\x12+\n" +
	"\x06ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\x12(\n" +
	"\arequest\x18\x03 \x01(\v2\x0e.paxos.RequestR\arequest\"l\n" +
	"\aNewView\x12+\n" +
	"\x06ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\x124\n" +
	"\n" +
	"accept_log\x18\x02 \x03(\v2\x15.paxos.AcceptLogEntryR\tacceptLog\"\xa1\x01\n" +
	"\x05Reply\x12+\n" +
	"\x06ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x16\n" +
	"\x06result\x18\x04 \x01(\bR\x06result\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"Q\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"W\n" +
	"\n" +
	"ClientInfo\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"p\n" +
	"\fSystemConfig\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.paxos.NodeInfoR\x05nodes\x12+\n" +
	"\aclients\x18\x02 \x03(\v2\x11.paxos.ClientInfoR\aclients\x12\f\n" +
	"\x01f\x18\x03 \x01(\x05R\x01f\":\n" +
	"\x06Status\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"=\n" +
	"\x12PrintStatusRequest\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x05R\x0esequenceNumber2\x99\x02\n" +
	"\fPaxosService\x12+\n" +
	"\vSendRequest\x12\x0e.paxos.Request\x1a\f.paxos.Reply\x12(\n" +
	"\tGetStatus\x12\f.paxos.Empty\x1a\r.paxos.Status\x12'\n" +
	"\bPrintLog\x12\f.paxos.Empty\x1a\r.paxos.Status\x12&\n" +
	"\aPrintDB\x12\f.paxos.Empty\x1a\r.paxos.Status\x127\n" +
	"\vPrintStatus\x12\x19.paxos.PrintStatusRequest\x1a\r.paxos.Status\x12(\n" +
	"\tPrintView\x12\f.paxos.Empty\x1a\r.paxos.Status2\xbe\x03\n" +
	"\vNodeService\x122\n" +
	"\rHandlePrepare\x12\x0e.paxos.Prepare\x1a\x11.paxos.PrepareAck\x12.\n" +
	"\rHandlePromise\x12\x0e.paxos.Promise\x1a\r.paxos.Status\x12/\n" +
	"\fHandleAccept\x12\r.paxos.Accept\x1a\x10.paxos.AcceptAck\x120\n" +
	"\x0eHandleAccepted\x12\x0f.paxos.Accepted\x1a\r.paxos.Status\x12,\n" +
	"\fHandleCommit\x12\r.paxos.Commit\x1a\r.paxos.Status\x12.\n" +
	"\rHandleNewView\x12\x0e.paxos.NewView\x1a\r.paxos.Status\x12.\n" +
	"\rHandleRequest\x12\x0e.paxos.Request\x1a\r.paxos.Status\x12.\n" +
	"\x0eRequestNewView\x12\f.paxos.Empty\x1a\x0e.paxos.NewView\x12*\n" +
	"\tGetLeader\x12\f.paxos.Empty\x1a\x0f.paxos.NodeInfo29\n" +
	"\rClientService\x12(\n" +
	"\tSendReply\x12\f.paxos.Reply\x1a\r.paxos.StatusB\tZ\a./protob\x06proto3"

var (
	file_proto_paxos_proto_rawDescOnce sync.Once
	file_proto_paxos_proto_rawDescData []byte
)

func file_proto_paxos_proto_rawDescGZIP() []byte {
	file_proto_paxos_proto_rawDescOnce.Do(func() {
		file_proto_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paxos_proto_rawDesc), len(file_proto_paxos_proto_rawDesc)))
	})
	return file_proto_paxos_proto_rawDescData
}

var file_proto_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_paxos_proto_goTypes = []any{
	(*BallotNumber)(nil),       // 0: paxos.BallotNumber
	(*Transaction)(nil),        // 1: paxos.Transaction
	(*Request)(nil),            // 2: paxos.Request
	(*Prepare)(nil),            // 3: paxos.Prepare
	(*Promise)(nil),            // 4: paxos.Promise
	(*PrepareAck)(nil),         // 5: paxos.PrepareAck
	(*AcceptLogEntry)(nil),     // 6: paxos.AcceptLogEntry
	(*Accept)(nil),             // 7: paxos.Accept
	(*AcceptAck)(nil),          // 8: paxos.AcceptAck
	(*Accepted)(nil),           // 9: paxos.Accepted
	(*Commit)(nil),             // 10: paxos.Commit
	(*NewView)(nil),            // 11: paxos.NewView
	(*Reply)(nil),              // 12: paxos.Reply
	(*NodeInfo)(nil),           // 13: paxos.NodeInfo
	(*ClientInfo)(nil),         // 14: paxos.ClientInfo
	(*SystemConfig)(nil),       // 15: paxos.SystemConfig
	(*Status)(nil),             // 16: paxos.Status
	(*Empty)(nil),              // 17: paxos.Empty
	(*PrintStatusRequest)(nil), // 18: paxos.PrintStatusRequest
}
var file_proto_paxos_proto_depIdxs = []int32{
	1,  // 0: paxos.Request.transaction:type_name -> paxos.Transaction
	0,  // 1: paxos.Prepare.ballot:type_name -> paxos.BallotNumber
	0,  // 2: paxos.Promise.ballot:type_name -> paxos.BallotNumber
	6,  // 3: paxos.Promise.accept_log:type_name -> paxos.AcceptLogEntry
	0,  // 4: paxos.PrepareAck.ballot:type_name -> paxos.BallotNumber
	0,  // 5: paxos.AcceptLogEntry.accept_num:type_name -> paxos.BallotNumber
	2,  // 6: paxos.AcceptLogEntry.accept_val:type_name -> paxos.Request
	0,  // 7: paxos.Accept.ballot:type_name -> paxos.BallotNumber
	2,  // 8: paxos.Accept.request:type_name -> paxos.Request
	0,  // 9: paxos.Accepted.ballot:type_name -> paxos.BallotNumber
	2,  // 10: paxos.Accepted.request:type_name -> paxos.Request
	0,  // 11: paxos.Commit.ballot:type_name -> paxos.BallotNumber
	2,  // 12: paxos.Commit.request:type_name -> paxos.Request
	0,  // 13: paxos.NewView.ballot:type_name -> paxos.BallotNumber
	6,  // 14: paxos.NewView.accept_log:type_name -> paxos.AcceptLogEntry
	0,  // 15: paxos.Reply.ballot:type_name -> paxos.BallotNumber
	13, // 16: paxos.SystemConfig.nodes:type_name -> paxos.NodeInfo
	14, // 17: paxos.SystemConfig.clients:type_name -> paxos.ClientInfo
	2,  // 18: paxos.PaxosService.SendRequest:input_type -> paxos.Request
	17, // 19: paxos.PaxosService.GetStatus:input_type -> paxos.Empty
	17, // 20: paxos.PaxosService.PrintLog:input_type -> paxos.Empty
	17, // 21: paxos.PaxosService.PrintDB:input_type -> paxos.Empty
	18, // 22: paxos.PaxosService.PrintStatus:input_type -> paxos.PrintStatusRequest
	17, // 23: paxos.PaxosService.PrintView:input_type -> paxos.Empty
	3,  // 24: paxos.NodeService.HandlePrepare:input_type -> paxos.Prepare
	4,  // 25: paxos.NodeService.HandlePromise:input_type -> paxos.Promise
	7,  // 26: paxos.NodeService.HandleAccept:input_type -> paxos.Accept
	9,  // 27: paxos.NodeService.HandleAccepted:input_type -> paxos.Accepted
	10, // 28: paxos.NodeService.HandleCommit:input_type -> paxos.Commit
	11, // 29: paxos.NodeService.HandleNewView:input_type -> paxos.NewView
	2,  // 30: paxos.NodeService.HandleRequest:input_type -> paxos.Request
	17, // 31: paxos.NodeService.RequestNewView:input_type -> paxos.Empty
	17, // 32: paxos.NodeService.GetLeader:input_type -> paxos.Empty
	12, // 33: paxos.ClientService.SendReply:input_type -> paxos.Reply
	12, // 34: paxos.PaxosService.SendRequest:output_type -> paxos.Reply
	16, // 35: paxos.PaxosService.GetStatus:output_type -> paxos.Status
	16, // 36: paxos.PaxosService.PrintLog:output_type -> paxos.Status
	16, // 37: paxos.PaxosService.PrintDB:output_type -> paxos.Status
	16, // 38: paxos.PaxosService.PrintStatus:output_type -> paxos.Status
	16, // 39: paxos.PaxosService.PrintView:output_type -> paxos.Status
	5,  // 40: paxos.NodeService.HandlePrepare:output_type -> paxos.PrepareAck
	16, // 41: paxos.NodeService.HandlePromise:output_type -> paxos.Status
	8,  // 42: paxos.NodeService.HandleAccept:output_type -> paxos.AcceptAck
	16, // 43: paxos.NodeService.HandleAccepted:output_type -> paxos.Status
	16, // 44: paxos.NodeService.HandleCommit:output_type -> paxos.Status
	16, // 45: paxos.NodeService.HandleNewView:output_type -> paxos.Status
	16, // 46: paxos.NodeService.HandleRequest:output_type -> paxos.Status
	11, // 47: paxos.NodeService.RequestNewView:output_type -> paxos.NewView
	13, // 48: paxos.NodeService.GetLeader:output_type -> paxos.NodeInfo
	16, // 49: paxos.ClientService.SendReply:output_type -> paxos.Status
	34, // [34:50] is the sub-list for method output_type
	18, // [18:34] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_paxos_proto_init() }
func file_proto_paxos_proto_init() {
	if File_proto_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paxos_proto_rawDesc), len(file_proto_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_paxos_proto_goTypes,
		DependencyIndexes: file_proto_paxos_proto_depIdxs,
		MessageInfos:      file_proto_paxos_proto_msgTypes,
	}.Build()
	File_proto_paxos_proto = out.File
	file_proto_paxos_proto_goTypes = nil
	file_proto_paxos_proto_depIdxs = nil
}
